-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 11:47:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema joutes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `joutes` ;

-- -----------------------------------------------------
-- Schema joutes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joutes` DEFAULT CHARACTER SET utf8 ;
USE `joutes` ;

-- -----------------------------------------------------
-- Table `joutes`.`Sports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joutes`.`Sports` ;

CREATE TABLE IF NOT EXISTS `joutes`.`Sports` (
                                                 `idSports` INT NOT NULL AUTO_INCREMENT,
                                                 `Name` VARCHAR(25) NOT NULL,
    `DateHourBegin` DATETIME NOT NULL,
    `DateHourEnd` DATETIME NOT NULL,
    PRIMARY KEY (`idSports`),
    UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joutes`.`Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joutes`.`Teams` ;

CREATE TABLE IF NOT EXISTS `joutes`.`Teams` (
                                                `idTeams` INT NOT NULL AUTO_INCREMENT,
                                                `Name` VARCHAR(15) NOT NULL,
    PRIMARY KEY (`idTeams`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joutes`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joutes`.`Players` ;

CREATE TABLE IF NOT EXISTS `joutes`.`Players` (
                                                  `idPlayers` INT NOT NULL AUTO_INCREMENT,
                                                  `Firstname` VARCHAR(20) NOT NULL,
    `Lastname` VARCHAR(20) NOT NULL,
    `Email` VARCHAR(45) NOT NULL,
    `Classname` VARCHAR(15) NOT NULL,
    `Teams_id` INT NOT NULL,
    PRIMARY KEY (`idPlayers`),
    INDEX `fk_Players_Teams_idx` (`Teams_id` ASC) VISIBLE,
    UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
    CONSTRAINT `fk_Players_Teams`
    FOREIGN KEY (`Teams_id`)
    REFERENCES `joutes`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `joutes`.`Sports_has_Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `joutes`.`Sports_has_Teams` ;

CREATE TABLE IF NOT EXISTS `joutes`.`Sports_has_Teams` (
    `idParticipate` INT NOT NULL AUTO_INCREMENT,
    `idSports` INT NOT NULL,
    `idTeams` INT NOT NULL,
    INDEX `fk_Sports_has_Teams_Teams1_idx` (`idTeams` ASC) VISIBLE,
    INDEX `fk_Sports_has_Teams_Sports1_idx` (`idSports` ASC) VISIBLE,
    PRIMARY KEY (`idParticipate`),
    CONSTRAINT `fk_Sports_has_Teams_Sports1`
    FOREIGN KEY (`idSports`)
    REFERENCES `joutes`.`Sports` (`idSports`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Sports_has_Teams_Teams1`
    FOREIGN KEY (`idTeams`)
    REFERENCES `joutes`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ) ENGINE = INNODB;

DROP TABLE IF EXISTS `joutes`.`Users` ;

CREATE TABLE IF NOT EXISTS `joutes`. `Users` (
    `idUsers` INT NOT NULL AUTO_INCREMENT,
    `Username` VARCHAR(25) NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    `Role` ENUM('admin', 'leader') NOT NULL DEFAULT 'leader',
    `Players_id` INT NULL,
    PRIMARY KEY (`idUsers`),
    UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
    CONSTRAINT `fk_Users_Players`
    FOREIGN KEY (`Players_id`)
    REFERENCES `joutes`.`Players` (`idPlayers`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION
    ) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
