name: CI Node

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: echo "npm install..."

      - name: Lancer les tests
        run: echo "Running tests..."