name: condition.yml
on: push

jobs:
  ma-condition:
    runs-on: ubuntu-latest

    steps:

      - name: Étape 1
        run: echo "Test OK"

      - name: Étape 2
        if: github.ref == 'refs/heads/main'
        run: echo "Deploiement en cours..."
