name: Lecture de Fichier
on: push
jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      # Étape indispensable pour accéder à vos fichiers
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Afficher le contenu du dossier
        run: ls -la

      - name: Lire le message
      # Complétez la commande pour afficher le contenu de message.txt
        run: cat message.txt