name: variables.yml
on: push

jobs:
  mon-job:
    runs-on: ubuntu-latest
    env:
      PRENOM: "Imad" # Remplacez par votre prénom
    steps:
    - name: Salutation personnalisée
      run: echo "Bonjour $PRENOM, bienvenue dans le module ICT324"
